---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xacmedatabases.acme.com
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: acme.com/v1
    kind: XAcmeDatabase
  resources:
    - name: DBInstance
      base:
        apiVersion: sql.gcp.upbound.io/v1beta1
        kind: DatabaseInstance
        spec:
          forProvider:
            databaseVersion: POSTGRES_13
            deletionProtection: false
            region: us-west2
            settings:
              - diskSize: 5
                tier: db-f1-micro
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        # buggy patch! the field is actually diskSize
        - fromFieldPath: spec.storageGB
          toFieldPath: spec.forProvider.settings[0].discSize
      connectionDetails:
        - fromConnectionSecretKey: connectionName
        - fromConnectionSecretKey: publicIP
        - fromConnectionSecretKey: serverCACertificateCert
        - type: FromValue
          name: port
          value: "5432"